//! Integration tests for the Credential Registry contract.
//!
//! These are placeholder test stubs. Each test describes the behaviour that
//! must be verified once the corresponding contract function is implemented.
//!
//! Run with:
//!   cargo test --package credential_registry

#[cfg(test)]
mod tests {
    // Future: use soroban_sdk::testutils and the contract client generated by
    // soroban_sdk::contractimpl to deploy the contract in a local test
    // environment and call its methods.

    /// Verify that a valid issuer can register a new credential hash.
    ///
    /// Expected behaviour:
    /// - Transaction succeeds.
    /// - Querying the hash returns the correct issuer, holder, and timestamp.
    /// - `revoked` flag is false.
    #[test]
    #[ignore = "not yet implemented"]
    fn test_issue_credential() {}

    /// Verify that revoking a credential marks it as revoked.
    ///
    /// Expected behaviour:
    /// - Only the original issuer (or admin) can revoke.
    /// - After revocation, querying the hash returns `revoked = true`.
    /// - Revocation cannot be undone.
    #[test]
    #[ignore = "not yet implemented"]
    fn test_revoke_credential() {}

    /// Verify that a credential hash can be looked up and its status confirmed.
    ///
    /// Expected behaviour:
    /// - Returns issuer, holder, timestamp, and revocation status.
    /// - Returns an error / None for unknown hashes.
    #[test]
    #[ignore = "not yet implemented"]
    fn test_verify_credential() {}

    /// Verify that unauthorized callers cannot issue or revoke credentials.
    ///
    /// Expected behaviour:
    /// - Calls from non-allowlisted addresses are rejected.
    /// - Contract panics / returns an auth error.
    #[test]
    #[ignore = "not yet implemented"]
    fn test_authorization() {}
}
